// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gibbs
NumericMatrix gibbs(int N, int thin);
RcppExport SEXP chRonos_gibbs(SEXP NSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    int N = Rcpp::as<int >(NSEXP);
    int thin = Rcpp::as<int >(thinSEXP);
    NumericMatrix __result = gibbs(N, thin);
    return Rcpp::wrap(__result);
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP chRonos_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    List __result = rcpp_hello_world();
    return Rcpp::wrap(__result);
END_RCPP
}
